from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession

from app.schemas.skill_fabric import (
    AgentSkillCreate,
    AgentSkillRead,
    AgentSkillVersionRead,
    SkillCandidateRead,
    SkillEvaluationRead,
    SkillHealthRead,
    SkillInvokeRequest,
    SkillInvokeResponse,
    SkillDeployRequest,
    SkillFeedbackRequest
)
from app.services import skill_fabric_service
from app.dependencies.db import get_db
from app.dependencies.auth import get_current_workspace, require_admin, WorkspaceContext

router = APIRouter(prefix="/agents", tags=["Enterprise Agent Skill Fabric & Controlled Skill Evolution"])

@router.get("/skills", response_model=List[AgentSkillRead])
async def list_skills(
    ws_ctx: WorkspaceContext = Depends(get_current_workspace),
    db: AsyncSession = Depends(get_db)
):
    """Lists active workspace agent skills."""
    return await skill_fabric_service.list_skills(db, workspace_id=ws_ctx.workspace_id)

@router.post("/skills", response_model=AgentSkillRead)
async def create_skill(
    req: AgentSkillCreate,
    ws_ctx: WorkspaceContext = Depends(get_current_workspace),
    db: AsyncSession = Depends(get_db)
):
    """Creates a new versioned agent skill."""
    skill, _ = await skill_fabric_service.create_skill(
        db, workspace_id=ws_ctx.workspace_id, req=req, organization_id=ws_ctx.workspace_id
    )
    return skill

@router.get("/skill-candidates", response_model=List[SkillCandidateRead])
async def list_candidates(
    ws_ctx: WorkspaceContext = Depends(get_current_workspace),
    db: AsyncSession = Depends(get_db)
):
    """Lists unvalidated skill candidates generated by pattern detection."""
    return await skill_fabric_service.list_candidates(db, workspace_id=ws_ctx.workspace_id)

@router.get("/skills/{skill_id}", response_model=AgentSkillRead)
async def get_skill(
    skill_id: str,
    ws_ctx: WorkspaceContext = Depends(get_current_workspace),
    db: AsyncSession = Depends(get_db)
):
    """Fetches skill details."""
    skill = await skill_fabric_service.get_skill(db, skill_id=skill_id)
    if not skill:
        raise HTTPException(status_code=404, detail="Skill not found")
    return skill

@router.get("/skills/{skill_id}/versions", response_model=List[AgentSkillVersionRead])
async def get_skill_versions(
    skill_id: str,
    ws_ctx: WorkspaceContext = Depends(get_current_workspace),
    db: AsyncSession = Depends(get_db)
):
    """Returns version history of a skill."""
    return await skill_fabric_service.get_versions(db, skill_id=skill_id)

@router.get("/skills/{skill_id}/health", response_model=SkillHealthRead)
async def get_skill_health(
    skill_id: str,
    ws_ctx: WorkspaceContext = Depends(get_current_workspace),
    db: AsyncSession = Depends(get_db)
):
    """Returns health metrics for the current active version of a skill."""
    skill = await skill_fabric_service.get_skill(db, skill_id=skill_id)
    if not skill or not skill.get("current_version_id"):
        raise HTTPException(status_code=404, detail="Skill active version not found")
    health = await skill_fabric_service.get_health(db, version_id=skill["current_version_id"])
    if not health:
        raise HTTPException(status_code=404, detail="Skill health telemetry not found")
    return health

@router.post("/skills/{skill_id}/invoke", response_model=SkillInvokeResponse)
async def invoke_skill(
    skill_id: str,
    req: SkillInvokeRequest,
    ws_ctx: WorkspaceContext = Depends(get_current_workspace),
    db: AsyncSession = Depends(get_db)
):
    """Invokes a versioned skill with PolicyEngine, DLP, and circular dependency checks."""
    return await skill_fabric_service.invoke_skill(
        db, workspace_id=ws_ctx.workspace_id, skill_id=skill_id, req=req, organization_id=ws_ctx.workspace_id
    )
